export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'But Ticket to Space',
    headline: 'we make Air and Space available for everyone',
    description: 'Building on the achievements of Falcon 9 and Falcon Heavy, SpaceX is working on a next generation of fully reusable launch vehicles that will be the most powerful ever built, capable of carrying humans to Mars and other destinations in the solar system',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg1.svg').default,
    alt: 'Space', 
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'DART MISSION',
    headline: 'We make Air and Space available for everyone',
    description: 'On Tuesday, November 23 at 10:21 p.m. PST, Falcon 9 launched NASA’s Double Asteroid Redirection Test (DART) mission to an interplanetary transfer orbit from Space Launch Complex 4 East (SLC-4E) at Vandenberg ',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg2.svg').default,
    alt: 'Space', 
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'HUMAN SPACEFLIGHT',
    headline: 'STARSHIP',
    description: 'SpaceX’s Starship spacecraft and Super Heavy rocket (collectively referred to as Starship) represent a fully reusable transportation system designed to carry both crew and cargo to Earth orbit, the Moon, Mars and beyond. Starship will be the world’s most powerful launch vehicle ever developed, with the ability to carry in excess of 100 metric tonnes to Earth orbit.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg3.svg').default,
    alt: 'Space', 
    dark: true,
    primary: true,
    darkText: false,
}